# Solving simultaneous equations using python

Given simultanious equations <br>
x + y + z = 6 <br>
2y + 5z = -4<br>
2x + 5y -z = 27<br> 

In [1]:
#import numpy for linear algebra
import numpy as np

Converting to Arrays <br>
Array 1  :[ [1,1,1], [0,2,5], [2,5,-1] ]

Array 2 : [6,-4,27]

In [2]:
#Converting to arrays and Assigning the simultanious equation to 3x3 array and 1x3 array.
A = [[1,1,1],[0,2,5],[2,5,-1]]
Y = [6,-4,27]
print(A)
print(Y)

[[1, 1, 1], [0, 2, 5], [2, 5, -1]]
[6, -4, 27]


In [3]:
#Compute the (multiplicative) inverse of a matrix of A  (Array 1)
res = np.linalg.inv(A)
print("INVERSE MATRIX OF ARRAY 1")
print(res)
#Compute the inverse matrix of A (Array 1)) with Array 2 (Y)
xyz=res.dot(Y)
print("\nX, Y, Z VALUES")
print(xyz)#Compute the inverse matrix of A (Array 1)) with Array 2 (Y)
xyz=res.dot(Y)
print("\nX, Y, Z VALUES")
print(xyz)

INVERSE MATRIX OF ARRAY 1
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]

X, Y, Z VALUES
[ 5.  3. -2.]


In [4]:
# assigning the outout array to the the respective variables x, y, z
x=round(xyz[0])
y=round(xyz[1])
z=round(xyz[2])
print(x,y,z)

5.0 3.0 -2.0


In [5]:
#validating the first equation with the output
1*x+1*y+1*z

6.0

In [6]:
#validating the second equation with output
2*y + 5*z

-4.0

In [7]:
#validating the third equation with output
2*x + 5*y -1*z

27.0